name: UnraveledMC-Mod
main: me.unraveledmc.unraveledmcmod.UnraveledMCMod
version: ${tfm.build.version}
description: Plugin for UnraveledMC.
depend: [Aero, WorldEdit]
softdepend: [BukkitTelnet, UMC-Essentials, LibsDisguises]
authors: [Madgeek1450, Prozza, CreeperSeth, AwesomePinch(CreeperIvanYT), aggelosQQ]

# plugin.yml is no longer used to define commands.
